version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: ":arrow_upper_right: [patch]"
      include: "scope"
    schedule:
      interval: "weekly"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/monitoring-idp-consumer"
    commit-message:
      prefix: ":arrow_upper_right: [patch]"
      include: "scope"
    schedule:
      interval: "weekly"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/monitoring-idp-producer"
    commit-message:
      prefix: ":arrow_upper_right: [patch]"
      include: "scope"
    schedule:
      interval: "weekly"
    versioning-strategy: increase

  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
    commit-message:
      prefix: ":arrow_upper_right: [patch]"
      include: "scope"
    schedule:
      interval: "weekly"
