server {
    listen 80;
    location /health {
        add_header Content-Type application/json;
        return 200 '{"status":"ok"}';
    }
}

server {
    listen 443 ssl;
    ssl_certificate /certs/valid.crt;
    ssl_certificate_key /certs/valid.key;

    location / {
        add_header Content-Type application/json;
        return 200 '{"status":"Rock authentication active"}';
    }
}
