services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    stop_signal: SIGKILL

  auth.fenris.spacewolves:
    image: nginx:alpine
    volumes:
      - ./auth.fenris.spacewolves.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1/health || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
    stop_signal: SIGKILL

  auth.prospero.thousandsons:
    image: nginx:alpine
    volumes:
      - ./auth.prospero.thousandsons.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1/health || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
    stop_signal: SIGKILL

  auth.sorcerers.thousandsons:
    image: nginx:alpine
    volumes:
      - ./auth.sorcerers.thousandsons.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1/health || exit 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 3
    stop_signal: SIGKILL

  producer:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: producer
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - IDP_URLS=["http://auth.fenris.spacewolves","http://auth.prospero.thousandsons","http://auth.sorcerers.thousandsons"]
      - QUEUE_PRODUCER_NAME=monitoring-producer
      - QUEUE_CONSUMER_NAME=monitoring-consumer
      - HTTP_TIMEOUT=10000
      - PORT=3000
    depends_on:
      rabbitmq:
        condition: service_healthy
      auth.fenris.spacewolves:
        condition: service_healthy
      auth.prospero.thousandsons:
        condition: service_healthy
      auth.sorcerers.thousandsons:
        condition: service_healthy
    stop_signal: SIGKILL

  consumer:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: consumer
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - QUEUE_PRODUCER_NAME=monitoring-producer
      - QUEUE_CONSUMER_NAME=monitoring-consumer
      - HTTP_TIMEOUT=10000
      - MAP_FI_NAMES_TO_URL={"fenris":"http://auth.fenris.spacewolves","prospero":"http://auth.prospero.thousandsons","sorcerers":"http://auth.sorcerers.thousandsons"}
    depends_on:
      rabbitmq:
        condition: service_healthy
      auth.fenris.spacewolves:
        condition: service_healthy
      auth.prospero.thousandsons:
        condition: service_healthy
      auth.sorcerers.thousandsons:
        condition: service_healthy
    stop_signal: SIGKILL

  test_runner:
    image: curlimages/curl:latest
    depends_on:
      - rabbitmq
      - auth.fenris.spacewolves
      - auth.prospero.thousandsons
      - auth.sorcerers.thousandsons
      - producer
      - consumer
    entrypoint: ["sleep", "infinity"]
    stop_signal: SIGKILL
